# Generated by Django 5.0.9 on 2024-11-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('mabaiviet', models.AutoField(db_column='MABAIVIET', primary_key=True, serialize=False)),
                ('magd', models.CharField(db_column='MAGD', max_length=10, null=True)),
                ('tieude', models.CharField(db_column='TIEUDE', max_length=75, null=True)),
                ('noidung', models.TextField(db_column='NOIDUNG', null=True)),
                ('thongtinlienlac', models.CharField(db_column='THONGTINLIENLAC', max_length=200, null=True)),
                ('mota', models.TextField(db_column='MOTA', null=True)),
                ('diachibaiviet', models.TextField(db_column='DIACHIBAIVIET', null=True)),
                ('giatri', models.DecimalField(db_column='GIATRI', decimal_places=4, max_digits=19, null=True)),
                ('ngaydang', models.DateField(db_column='NGAYDANG', null=True)),
                ('ngayhethan', models.DateField(db_column='NGAYHETHAN', null=True)),
                ('hangxe', models.CharField(db_column='HANGXE', max_length=15, null=True)),
                ('loaixe', models.CharField(db_column='LOAIXE', max_length=25, null=True)),
                ('nammua', models.IntegerField(db_column='NAMMUA', null=True)),
                ('dungtich', models.CharField(db_column='DUNGTICH', max_length=50, null=True)),
                ('sokmdadi', models.BigIntegerField(db_column='SOKMDADI', null=True)),
                ('baohanh', models.CharField(db_column='BAOHANH', max_length=40, null=True)),
                ('xuatxu', models.CharField(db_column='XUATXU', max_length=30, null=True)),
                ('tinhtrangxe', models.CharField(db_column='TINHTRANGXE', max_length=30, null=True)),
                ('giaban', models.CharField(db_column='GIABAN', max_length=10, null=True)),
            ],
            options={
                'db_table': 'BAIVIET',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('iduser', models.CharField(db_column='MANGUOIDUNG', max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='TENDANGNHAP', max_length=20, null=True)),
                ('password', models.CharField(blank=True, db_column='MATKHAU', max_length=50, null=True)),
                ('fullname', models.CharField(blank=True, db_column='HOTEN', max_length=50, null=True)),
                ('birthdate', models.DateField(blank=True, db_column='NGAYSINH', null=True)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_column='DIACHI', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='SODIENTHOAI', max_length=12, null=True)),
                ('gender', models.CharField(blank=True, db_column='GIOITINH', max_length=4, null=True)),
                ('identity_card', models.CharField(blank=True, db_column='SOCCCD', max_length=12, null=True)),
                ('discription', models.TextField(blank=True, db_column='MOTA', null=True)),
                ('avatar', models.CharField(blank=True, db_column='ANHDAIDIEN', max_length=50, null=True)),
                ('background', models.CharField(blank=True, db_column='ANHNEN', max_length=10, null=True)),
                ('balance', models.DecimalField(blank=True, db_column='SODU', decimal_places=4, max_digits=19, null=True)),
                ('is_superuser', models.BooleanField(blank=True, db_column='is_superuser', null=True)),
            ],
            options={
                'db_table': 'NGUOIDUNG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoiGiaoDich',
            fields=[
                ('maloaigiaodich', models.CharField(db_column='MALOAIGIAODICH', max_length=10, primary_key=True, serialize=False)),
                ('tenloaigiaodich', models.CharField(db_column='TENLOAIGIAODICH', max_length=50)),
                ('sotien', models.DecimalField(db_column='SOTIEN', decimal_places=4, max_digits=19)),
                ('songay', models.SmallIntegerField(db_column='SONGAY')),
            ],
            options={
                'db_table': 'GOIGIAODICH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HinhAnh',
            fields=[
                ('mahinh', models.CharField(db_column='MAHINHANH', max_length=10, primary_key=True, serialize=False)),
                ('tenfile', models.CharField(blank=True, db_column='TENFILE', max_length=10, null=True)),
            ],
            options={
                'db_table': 'HINHANH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NapDayTin',
            fields=[
                ('magd', models.CharField(db_column='MAGD', max_length=10, primary_key=True, serialize=False)),
                ('ngay', models.DateTimeField(blank=True, db_column='NGAY', null=True)),
            ],
            options={
                'db_table': 'NAPDAYTIN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NapGiaHan',
            fields=[
                ('magiaodich', models.CharField(db_column='MAGIAODICH', max_length=10, primary_key=True, serialize=False)),
                ('sotien', models.DecimalField(blank=True, db_column='SOTIEN', decimal_places=4, max_digits=19, null=True)),
                ('ngaygiaodich', models.DateTimeField(db_column='NGAYGIAODICH')),
            ],
            options={
                'db_table': 'NAPGIAHAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NapTienTaiKhoan',
            fields=[
                ('magiaodich', models.CharField(db_column='MAGIAODICH', max_length=10, primary_key=True, serialize=False)),
                ('sotiennap', models.DecimalField(blank=True, db_column='SOTIENNAP', decimal_places=4, max_digits=19, null=True)),
                ('thoigiannap', models.DateTimeField(blank=True, db_column='THOIGIANNAP', null=True)),
            ],
            options={
                'db_table': 'NAPTIENTAIKHOAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('mathongbao', models.CharField(db_column='MATHONGBAO', max_length=10, primary_key=True, serialize=False)),
                ('tieude', models.CharField(blank=True, db_column='TIEUDE', max_length=50, null=True)),
                ('noidung', models.CharField(blank=True, db_column='NOIDUNG', max_length=256, null=True)),
                ('thoigiangui', models.DateTimeField(blank=True, db_column='THOIGIANGUI', null=True)),
            ],
            options={
                'db_table': 'THONGBAO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThuocTinhHeThong',
            fields=[
                ('logo', models.CharField(blank=True, db_column='Logo', max_length=50, null=True)),
                ('maugiaodien', models.CharField(blank=True, db_column='MauGiaoDien', max_length=10, null=True)),
                ('diachifooter', models.TextField(blank=True, db_column='DiaChiFooter', null=True)),
                ('thanhvienfooter', models.TextField(blank=True, db_column='ThanhVienFooter', null=True)),
                ('kenhtruyenthongfooter', models.TextField(blank=True, db_column='KenhTruyenThongFooter', null=True)),
                ('phuongthucthanhtoanfooter', models.TextField(blank=True, db_column='PhuongThucThanhToanFooter', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'THUOCTINHHETHONG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Follwer',
            fields=[
                ('followerid', models.ForeignKey(db_column='followerid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='following', serialize=False, to='CustomAdmin.nguoidung')),
                ('followedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Follwer',
                'managed': False,
            },
        ),
    ]
